spring:
  data:
    rest:
      base-path: /api
  security:
    user:
      name: buzz
      password: infinity
  datasource:
    generate-unique-name: false
    name: tacocloud

taco:
  orders:
    pageSize: 10


  discount:
    codes:
      abcdef: 10


---
spring:
  config:
    acitvate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword

logging:
  level:
    tacos: WARN

server:
  port: 8080

tacocloud:
  email:
    host: imap.tacocloud.com
    mailbox: INBOX
    username: taco-in-flow
    password: qwerty123
    poll-rate: 10000
