-- Сначала создаем таблицы без внешних ключей
CREATE TABLE IF NOT EXISTS Ingredient (
    id VARCHAR(4) PRIMARY KEY,
    name VARCHAR(25) NOT NULL,
    type VARCHAR(10) NOT NULL
);

-- Затем таблицы с простыми зависимостями
CREATE TABLE IF NOT EXISTS Taco_Order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_Name VARCHAR(50) NOT NULL,
    delivery_Street VARCHAR(50) NOT NULL,
    delivery_City VARCHAR(50) NOT NULL,
    delivery_State VARCHAR(2) NOT NULL,
    delivery_Zip VARCHAR(10) NOT NULL,
    cc_number VARCHAR(16) NOT NULL,
    cc_expiration VARCHAR(5) NOT NULL,
    cc_cvv VARCHAR(3) NOT NULL,
    placed_at TIMESTAMP NOT NULL,
    user_id BIGINT
);

-- Таблица с внешними ключами (исправлена синтаксическая ошибка)
CREATE TABLE IF NOT EXISTS Taco (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    taco_order_id BIGINT
    FOREIGN KEY (taco_order_id) REFERENCES Taco_Order(id)
);

-- Связующая таблица (добавлена после создания всех основных таблиц)
CREATE TABLE IF NOT EXISTS Ingredient_Ref (
    taco_id BIGINT NOT NULL,
    ingredient_id VARCHAR(4) NOT NULL,
    PRIMARY KEY (taco_id, ingredient_id),
    FOREIGN KEY (taco_id) REFERENCES Taco(id),
    FOREIGN KEY (ingredient_id) REFERENCES Ingredient(id)
);